spring.application.name=fluxpuzzles

# Puerto de la aplicación (Spring Boot)
server.port=${PORT:8080}

# Clave secreta para JWT (se resuelve desde variable de entorno JWT_SECRET)
jwt.secret=${UnaClaveSecretaMuyLargaYSuperSeguraDeAlMenos32Caracteres}

# Conexión a la Base de Datos (MySQL)
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3307/fluxpuzzles?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# API Externa (Reto Diario)
jsonplaceholder.base-url=https://jsonplaceholder.typicode.com